
title: SUNY Potsdam ACM
name: SUNY Potsdam ACM homepage

include:
- _pages

collections:
  blog:
    permalink: /blog/:path/
    output: true
  guides:
    permalink: /guides/:path/
    output: true

exclude:
- README.md
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- whatthefuck.md
