
title: SUNY Potsdam ACM
name: SUNY Potsdam ACM homepage

exclude:
- README.md
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- whatthefuck.md
