
title: SUNY Potsdam ACM
name: SUNY Potsdam ACM homepage

include:
- _pages

pages_list:
  About: '/about'
  Join: '/join'
  ACM-W: '/acmw'
  Eboard: '/org'
  Blog: '/blog'
  Donate: '/donate'

collections:
  blog:
    permalink: /blog/:path/
    output: true

exclude:
- README.md
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- whatthefuck.md
